set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(AARCH64_BIN_PATH $ENV{AARCH64_PATH} CACHE PATH "path of aarch64-linux-gnu-xxx")
if (EXISTS ${AARCH64_BIN_PATH})
    set(CMAKE_C_COMPILER ${AARCH64_BIN_PATH}/aarch64-linux-gnu-gcc)
    set(CMAKE_CXX_COMPILER ${AARCH64_BIN_PATH}/aarch64-linux-gnu-g++)
    set(CMAKE_ASM_COMPILER ${AARCH64_BIN_PATH}/aarch64-linux-gnu-as)
    set(CMAKE_STRIP ${AARCH64_BIN_PATH}/aarch64-linux-gnu-strip)
    set(CMAKE_OBJCOPY ${AARCH64_BIN_PATH}/aarch64-linux-gnu-objcopy)
    set(CMAKE_AR ${AARCH64_BIN_PATH}/aarch64-linux-gnu-ar)
    set(CMAKE_RANLIB ${AARCH64_BIN_PATH}/aarch64-linux-gnu-ranlib)
else()
    set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
    set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
    set(CMAKE_ASM_COMPILER aarch64-linux-gnu-as)
    set(CMAKE_STRIP aarch64-linux-gnu-strip)
    set(CMAKE_OBJCOPY aarch64-linux-gnu-objcopy)
    set(CMAKE_AR aarch64-linux-gnu-ar)
    set(CMAKE_RANLIB aarch64-linux-gnu-ranlib)
endif()
